<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Investment;
use App\Models\InvestmentTransaction;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class InvestmentTransactionController extends Controller
{
    /**
     * Display all transactions for a specific investment
     */
    public function index(Investment $investment)
    {
        $transactions = $investment->transactions()
            ->orderBy('transaction_date', 'asc')
            ->get();

        return response()->json([
            'data' => $transactions->map(function ($transaction) {
                return [
                    'id' => $transaction->id,
                    'investment_id' => $transaction->investment_id,
                    'transaction_type' => $transaction->transaction_type,
                    'amount' => $transaction->amount,
                    'transaction_date' => $transaction->transaction_date,
                    'notes' => $transaction->notes,
                    'created_at' => $transaction->created_at,
                ];
            })->values(),
            'summary' => [
                'total_transactions' => $transactions->count(),
                'total_amount' => $transactions->sum('amount'),
            ],
        ]);
    }

    /**
     * Store a new investment transaction
     */
    public function store(Request $request, Investment $investment)
    {
        $validated = $request->validate([
            'transaction_type' => ['required', 'string', Rule::in(InvestmentTransaction::TYPES)],
            'amount' => 'required|numeric|min:0.01',
            'transaction_date' => 'required|date',
            'notes' => 'nullable|string',
        ]);

        if (($validated['transaction_type'] ?? null) === InvestmentTransaction::TYPE_CAPITAL_RAISE) {
            return response()->json([
                'message' => 'Capital Raise transactions can only be generated by publishing a Capital Raise.',
            ], 422);
        }

        if (($validated['transaction_type'] ?? null) === InvestmentTransaction::TYPE_INITIAL_CAPITALIZATION) {
            return response()->json([
                'message' => 'Initial Capitalization transaction type is deprecated. Use Initial Investment instead.',
            ], 422);
        }

        if (($validated['transaction_type'] ?? null) === InvestmentTransaction::TYPE_INITIAL
            && $investment->transactions()->where('transaction_type', InvestmentTransaction::TYPE_INITIAL)->exists()) {
            $existingInitial = $investment->transactions()
                ->where('transaction_type', InvestmentTransaction::TYPE_INITIAL)
                ->orderBy('id')
                ->first();

            return response()->json([
                'message' => 'Initial Investment transaction already exists for this investment.',
                'data' => [
                    'id' => $existingInitial?->id,
                    'investment_id' => $existingInitial?->investment_id,
                    'transaction_type' => $existingInitial?->transaction_type,
                    'amount' => $existingInitial?->amount,
                    'transaction_date' => $existingInitial?->transaction_date,
                    'notes' => $existingInitial?->notes,
                    'created_at' => $existingInitial?->created_at,
                ],
                'meta' => [
                    'idempotent' => true,
                ],
            ], 200);
        }

        $transaction = $investment->transactions()->create([
            'transaction_type' => $validated['transaction_type'],
            'amount' => $validated['amount'],
            'transaction_date' => $validated['transaction_date'],
            'notes' => $validated['notes'] ?? null,
            'source' => 'Manual',
            'status' => 'Posted',
            'is_read_only' => false,
        ]);

        $investment->update([
            'amount' => (float) $investment->transactions()->sum('amount'),
        ]);

        return response()->json([
            'message' => 'Investment transaction created successfully',
            'data' => [
                'id' => $transaction->id,
                'investment_id' => $transaction->investment_id,
                'transaction_type' => $transaction->transaction_type,
                'amount' => $transaction->amount,
                'transaction_date' => $transaction->transaction_date,
                'notes' => $transaction->notes,
                'created_at' => $transaction->created_at,
            ],
        ], 201);
    }

    /**
     * Display a specific investment transaction
     */
    public function show(Investment $investment, InvestmentTransaction $transaction)
    {
        // Verify transaction belongs to investment
        if ($transaction->investment_id !== $investment->id) {
            return response()->json([
                'message' => 'Transaction not found for this investment',
            ], 404);
        }

        return response()->json([
            'data' => [
                'id' => $transaction->id,
                'investment_id' => $transaction->investment_id,
                'transaction_type' => $transaction->transaction_type,
                'amount' => $transaction->amount,
                'transaction_date' => $transaction->transaction_date,
                'notes' => $transaction->notes,
                'created_at' => $transaction->created_at,
            ],
        ]);
    }

    /**
     * Update an investment transaction
     */
    public function update(Request $request, Investment $investment, InvestmentTransaction $transaction)
    {
        // Verify transaction belongs to investment
        if ($transaction->investment_id !== $investment->id) {
            return response()->json([
                'message' => 'Transaction not found for this investment',
            ], 404);
        }

        if ($transaction->is_read_only || $transaction->transaction_type === InvestmentTransaction::TYPE_CAPITAL_RAISE) {
            return response()->json([
                'message' => 'Generated Capital Raise transactions are read-only.',
            ], 422);
        }

        $validated = $request->validate([
            'transaction_type' => ['required', 'string', Rule::in(InvestmentTransaction::TYPES)],
            'amount' => 'required|numeric|min:0.01',
            'transaction_date' => 'required|date',
            'notes' => 'nullable|string',
        ]);

        if (($validated['transaction_type'] ?? null) === InvestmentTransaction::TYPE_INITIAL_CAPITALIZATION) {
            return response()->json([
                'message' => 'Initial Capitalization transaction type is deprecated. Use Initial Investment instead.',
            ], 422);
        }

        if (($validated['transaction_type'] ?? null) === InvestmentTransaction::TYPE_INITIAL
            && $investment->transactions()
                ->where('transaction_type', InvestmentTransaction::TYPE_INITIAL)
                ->where('id', '!=', $transaction->id)
                ->exists()) {
            return response()->json([
                'message' => 'Initial Investment transaction already exists for this investment. Use Additional Investment.',
            ], 422);
        }

        $transaction->update([
            'transaction_type' => $validated['transaction_type'],
            'amount' => $validated['amount'],
            'transaction_date' => $validated['transaction_date'],
            'notes' => $validated['notes'] ?? null,
        ]);

        $investment->update([
            'amount' => (float) $investment->transactions()->sum('amount'),
        ]);

        return response()->json([
            'message' => 'Investment transaction updated successfully',
            'data' => [
                'id' => $transaction->id,
                'investment_id' => $transaction->investment_id,
                'transaction_type' => $transaction->transaction_type,
                'amount' => $transaction->amount,
                'transaction_date' => $transaction->transaction_date,
                'notes' => $transaction->notes,
                'created_at' => $transaction->created_at,
            ],
        ]);
    }

    /**
     * Delete an investment transaction
     */
    public function destroy(Investment $investment, InvestmentTransaction $transaction)
    {
        // Verify transaction belongs to investment
        if ($transaction->investment_id !== $investment->id) {
            return response()->json([
                'message' => 'Transaction not found for this investment',
            ], 404);
        }

        if ($transaction->is_read_only || $transaction->transaction_type === InvestmentTransaction::TYPE_CAPITAL_RAISE) {
            return response()->json([
                'message' => 'Generated Capital Raise transactions are read-only.',
            ], 422);
        }

        $transaction->delete();

        $investment->update([
            'amount' => (float) $investment->transactions()->sum('amount'),
        ]);

        return response()->json([
            'message' => 'Investment transaction deleted successfully',
        ]);
    }
}
